# Generated by Django 4.2.16 on 2024-09-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffno', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('personnelarea', models.CharField(max_length=100, null=True)),
                ('organizationalarea', models.CharField(max_length=100, null=True)),
                ('personnelsubarea', models.CharField(max_length=100, null=True)),
                ('telephoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('idno', models.CharField(max_length=20, null=True)),
                ('krapin', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
