# Generated by Django 4.2.16 on 2024-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_staffvehicle_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='logbook',
            field=models.FileField(blank=True, null=True, upload_to='companylogbooks/'),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='logbook',
            field=models.FileField(blank=True, null=True, upload_to='stafflogbooks/'),
        ),
    ]
