# Generated by Django 4.2.16 on 2024-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_companyvehicle_logbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='employmentstatus',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('director/manager', 'Director/Manager'), ('ex-staff', 'Ex-Staff'), ('ex-director/manager', 'Ex-Director/Manager')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='typeofvehicle',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('commercial', 'Commercial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='logbook',
            field=models.FileField(null=True, upload_to='stafflogbooks/'),
        ),
    ]
