# Generated by Django 4.2.16 on 2024-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_premium_employmentstatus_premium_typeofvehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staffno', models.CharField(max_length=20, null=True)),
                ('natureoffeedback', models.CharField(choices=[('inquiry', 'Inquiry'), ('compliment', 'Compliment'), ('complaint', 'Complaint'), ('generalcomment', 'General Comment'), ('technicalissue', 'Technical Issue')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
