# Generated by Django 5.0.3 on 2024-09-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_motordetail_yom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motordetail',
            name='canceldate',
        ),
        migrations.RemoveField(
            model_name='motordetail',
            name='chasisno',
        ),
        migrations.RemoveField(
            model_name='motordetail',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='motordetail',
            name='make',
        ),
        migrations.RemoveField(
            model_name='motordetail',
            name='rating',
        ),
    ]
