# Generated by Django 5.0.3 on 2024-09-09 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_motordetail_canceldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordetail',
            name='canceldate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='chasisno',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='logbook',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='make',
            field=models.CharField(default='Unknown Make', max_length=100),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='rating',
            field=models.CharField(default='Unrated', max_length=100),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='yom',
            field=models.IntegerField(default=2000),
        ),
    ]
