# Generated by Django 5.0.3 on 2024-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_motordetail_canceldate_motordetail_chasisno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motordetail',
            name='canceldate',
        ),
        migrations.AddField(
            model_name='motordetail',
            name='dateofcancel',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
