# Generated by Django 5.0.3 on 2024-09-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_motordetail_canceldate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personnel_area', models.CharField(max_length=100)),
                ('organizational_area', models.CharField(max_length=100)),
                ('personnel_subarea', models.CharField(max_length=100)),
                ('telephone_no', models.IntegerField()),
                ('id_no', models.IntegerField()),
                ('kra_pin', models.CharField(max_length=100)),
                ('motor_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.motordetail')),
            ],
        ),
    ]
