# Generated by Django 5.0.3 on 2024-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motordetail',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='telephone_no',
            field=models.CharField(max_length=15),
        ),
    ]
