# Generated by Django 5.0.3 on 2024-09-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_motordetail_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='motor_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.motordetail'),
        ),
    ]
