# Generated by Django 5.0.3 on 2024-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_staffmember_first_name_alter_staffmember_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='personnel_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
