# Generated by Django 5.0.3 on 2024-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_staffmember_personnel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='personnel_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
