# Generated by Django 5.0.3 on 2024-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_staffmember_personnel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='personnel_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
