# Generated by Django 5.0.3 on 2024-09-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_staffmember_personnel_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REG_NUMBER', models.CharField(blank=True, max_length=100, null=True)),
                ('NAME_OF_INSURED', models.CharField(blank=True, max_length=100, null=True)),
                ('STAFF_NUMBER', models.IntegerField(blank=True, null=True)),
                ('AREA', models.CharField(blank=True, max_length=100, null=True)),
                ('COMMENCEMENT_DATE', models.DateField(blank=True, null=True)),
                ('EXPIRY_DATE', models.DateField(blank=True, null=True)),
                ('SUM_INSURED', models.IntegerField(blank=True, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_OF_CANCEL', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='motor_detail',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='Staff_Motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.staffmotor'),
        ),
    ]
