# Generated by Django 5.0.3 on 2024-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_staffmotor_remove_staffmember_motor_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
