# Generated by Django 5.0.3 on 2024-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REG_NUMBER', models.CharField(blank=True, max_length=100, null=True)),
                ('NAME_OF_INSURED', models.CharField(blank=True, max_length=100, null=True)),
                ('STAFF_NUMBER', models.IntegerField(blank=True, null=True)),
                ('AREA', models.CharField(blank=True, max_length=100, null=True)),
                ('DAMAGE_TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_OF_LOSS', models.DateField(blank=True, default=None, null=True)),
                ('DATE_OF_REPORT', models.DateField(blank=True, default=None, null=True)),
                ('CLAIM_DOCUMENT', models.FileField(blank=True, default=None, upload_to='uploads/')),
                ('REPAIR_ESTIMATE', models.CharField(blank=True, max_length=100, null=True)),
                ('REMARKS', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
