# Generated by Django 5.0.3 on 2024-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_directorsandmanagermotor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExDirectorsAndManagerMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REG_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('NAME_OF_INSURED', models.CharField(blank=True, max_length=100, null=True)),
                ('STAFF_NO', models.IntegerField(blank=True, null=True)),
                ('KRA_PIN', models.CharField(blank=True, max_length=100, null=True)),
                ('ID_NO', models.IntegerField(blank=True, null=True)),
                ('CHASSIS_NUMBER', models.CharField(blank=True, max_length=100, null=True)),
                ('MAKE_AND_MODEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RATING', models.CharField(blank=True, max_length=100, null=True)),
                ('YOM', models.IntegerField(blank=True, null=True)),
                ('SUM_INSURED', models.IntegerField(blank=True, null=True)),
                ('COMMENCEMENT_DATE', models.DateField(blank=True, null=True)),
                ('EXPIRY_DATE', models.DateField(blank=True, null=True)),
                ('LOGBOOK', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_OF_CANCEL', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
