# Generated by Django 5.0.3 on 2024-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_exstaffmotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialmotor',
            name='VALUE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directorsandmanagermotor',
            name='VALUE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exdirectorsandmanagermotor',
            name='SUM_INSURED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exstaffmotor',
            name='VALUE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmotor',
            name='SUM_INSURED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
