# Generated by Django 5.0.3 on 2024-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_motordetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordetail',
            name='employmentstatus',
            field=models.CharField(choices=[('staff', 'Staff'), ('director/manager', 'Director/Manager'), ('ex-staff', 'Ex-Staff'), ('ex-director/manager', 'Ex-Director/Manager')], default='staff', max_length=100),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='typeofcover',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('thirdparty', 'ThirdParty')], default='comprehensive', max_length=100),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='typeofvehicle',
            field=models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], default='private', max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=100),
        ),
    ]
