# Generated by Django 5.0.3 on 2024-09-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_motordetail_employmentstatus_motordetail_typeofcover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motordetail',
            old_name='expirydate',
            new_name='dateofcancelorexpiry',
        ),
        migrations.RemoveField(
            model_name='motordetail',
            name='dateofcancel',
        ),
    ]
