# Generated by Django 5.0.3 on 2024-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_expirydate_motordetail_dateofcancelorexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motordetail',
            name='chasisno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='employmentstatus',
            field=models.CharField(choices=[('staff', 'Staff'), ('director/manager', 'Director/Manager'), ('ex-staff', 'Ex-Staff'), ('ex-director/manager', 'Ex-Director/Manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='logbook',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='rating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='typeofcover',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('thirdparty', 'ThirdParty')], max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='typeofvehicle',
            field=models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='motordetail',
            name='yom',
            field=models.IntegerField(),
        ),
    ]
