# Generated by Django 5.0.3 on 2024-09-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_motordetail_chasisno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='Staff_Motor',
        ),
    ]
