# Generated by Django 5.0.3 on 2024-09-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_claim_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='CLAIM_DOCUMENT',
            new_name='claim_document',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='DAMAGE_TYPE',
            new_name='damage_type',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='DATE_OF_LOSS',
            new_name='date_of_loss',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='DATE_OF_REPORT',
            new_name='date_of_report',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='REMARKS',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='REPAIR_ESTIMATE',
            new_name='repair_estimate',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='VEHICLE',
            new_name='vehicle',
        ),
    ]
