# Generated by Django 5.0.3 on 2024-09-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_rename_claim_document_claim_claim_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.motordetail'),
        ),
    ]
