# Generated by Django 5.0.3 on 2024-09-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_claim_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
