# Generated by Django 5.0.3 on 2024-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_claim_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='vehicle',
        ),
    ]
