# Generated by Django 5.0.3 on 2024-09-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_remove_claim_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='claim',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.motordetail'),
        ),
    ]
