# Generated by Django 5.0.3 on 2024-09-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_remove_claim_reg_no_claim_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claim',
            new_name='StaffClaim',
        ),
    ]
