# Generated by Django 5.0.3 on 2024-09-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_rename_claim_staffclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('sumassured', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('chasisno', models.CharField(max_length=100)),
                ('yom', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=100)),
                ('commencementdate', models.DateField()),
                ('dateofcancelorexpiry', models.DateField()),
                ('logbook', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_loss', models.DateField(blank=True, default=None, null=True)),
                ('date_of_report', models.DateField(blank=True, default=None, null=True)),
                ('claim_document', models.FileField(blank=True, default=None, upload_to='uploads/')),
                ('repair_estimate', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.companyvehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffClaim',
        ),
    ]
