# Generated by Django 5.0.3 on 2024-09-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_companyvehicle_companyclaim_delete_staffclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_loss', models.DateField(blank=True, default=None, null=True)),
                ('date_of_report', models.DateField(blank=True, default=None, null=True)),
                ('claim_document', models.FileField(blank=True, default=None, upload_to='uploads/')),
                ('repair_estimate', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('staffno', models.IntegerField()),
                ('employmentstatus', models.CharField(choices=[('staff', 'Staff'), ('director/manager', 'Director/Manager'), ('ex-staff', 'Ex-Staff'), ('ex-director/manager', 'Ex-Director/Manager')], max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('area', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=15)),
                ('idno', models.IntegerField()),
                ('krapin', models.CharField(max_length=100)),
                ('sumassured', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('chasisno', models.CharField(max_length=100)),
                ('yom', models.IntegerField()),
                ('typeofvehicle', models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], max_length=100)),
                ('typeofcover', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('thirdparty', 'ThirdParty')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=100)),
                ('commencementdate', models.DateField()),
                ('dateofcancelorexpiry', models.DateField()),
                ('logbook', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='motordetail',
        ),
        migrations.AddField(
            model_name='staffclaim',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.staffvehicle'),
        ),
    ]
