# Generated by Django 5.0.3 on 2024-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_staffclaim_staffvehicle_delete_motordetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('staffno', models.IntegerField()),
                ('commencementdate', models.DateField()),
                ('dateofcancelorexpiry', models.DateField()),
                ('sumassured', models.IntegerField()),
                ('premiumrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prorata', models.IntegerField()),
                ('windscreenadditionalpremium', models.IntegerField()),
                ('radioadditionalpremium', models.IntegerField()),
                ('courtesycar', models.IntegerField()),
                ('excessprotector', models.CharField(blank=True, max_length=100)),
                ('grandtotal', models.IntegerField()),
                ('levies', models.IntegerField()),
                ('premiumpayable', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Payment Made'), ('unpaid', 'Payment Not Made')], max_length=100)),
                ('amountpaid', models.IntegerField()),
                ('paymentmethod', models.CharField(choices=[('cashpayment', 'Cash Payment'), ('salarydeduction', 'Salary Deduction')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffclaim',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Request Cover'), ('cancelled', 'Cancer Cover')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Request Cover'), ('cancelled', 'Cancel Cover')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CompanyClaim',
        ),
        migrations.DeleteModel(
            name='StaffClaim',
        ),
    ]
