# Generated by Django 5.0.3 on 2024-09-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_premium_remove_staffclaim_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='amountrefund',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='amountremaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='refundstatus',
            field=models.CharField(choices=[('refunded', 'Refund Made'), ('norefund', 'No Refund Made')], max_length=100, null=True),
        ),
    ]
