# Generated by Django 5.0.3 on 2024-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_premium_amountrefund_premium_amountremaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountpaid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountrefund',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountremaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='courtesycar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='excessprotector',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='grandtotal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='levies',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('cashpayment', 'Cash Payment'), ('salarydeduction', 'Salary Deduction'), ('otherpayment', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='premiumpayable',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='prorata',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='radioadditionalpremium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='refundstatus',
            field=models.CharField(blank=True, choices=[('refunded', 'Refund Made'), ('norefund', 'No Refund Made')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='staffno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Payment Made'), ('partpaid', 'Part Payment'), ('unpaid', 'Payment Not Made')], max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='windscreenadditionalpremium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], max_length=100),
        ),
    ]
