# Generated by Django 5.0.3 on 2024-09-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_companyvehicle_status_alter_premium_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='amountpaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountrefund',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountremaining',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='courtesycar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='excessprotector',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='levies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='premiumpayable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='prorata',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='radioadditionalpremium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='status',
            field=models.CharField(choices=[('paid', 'Payment Made'), ('partpaid', 'Part Payment'), ('unpaid', 'Payment Not Made')], max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='windscreenadditionalpremium',
            field=models.IntegerField(default=0),
        ),
    ]
