# Generated by Django 5.0.3 on 2024-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_premium_amountpaid_alter_premium_amountrefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='amountpaid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountrefund',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountremaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
