# Generated by Django 5.0.3 on 2024-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_premium_amountpaid_alter_premium_amountrefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], max_length=100),
        ),
    ]
