# Generated by Django 5.0.3 on 2024-09-13 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_staffvehicle_dateofcancelorexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='active', max_length=100),
        ),
    ]
