# Generated by Django 5.0.3 on 2024-09-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_staffvehicle_dateofcancelorexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='status',
            field=models.CharField(choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100),
        ),
    ]
