# Generated by Django 5.0.3 on 2024-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_alter_staffvehicle_dateofcancelorexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100),
        ),
    ]
