# Generated by Django 5.0.3 on 2024-09-13 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_staffvehicle_dateofcancelorexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(default=datetime.date(2024, 9, 13), null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100),
        ),
    ]
