# Generated by Django 5.0.3 on 2024-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_alter_staffvehicle_dateofcancelorexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='chasisno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='commencementdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='sumassured',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='yom',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountpaid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountrefund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='amountremaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='grandtotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='levies',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='premiumpayable',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='prorata',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='staffno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='dateofcancelorexpiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
