# Generated by Django 5.0.3 on 2024-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_alter_companyvehicle_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='logbook',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
