# Generated by Django 5.0.3 on 2024-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_alter_companyvehicle_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='logbook',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
