# Generated by Django 5.0.3 on 2024-09-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_alter_staffvehicle_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='chasisno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='commencementdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='employmentstatus',
            field=models.CharField(choices=[('staff', 'Staff'), ('director/manager', 'Director/Manager'), ('ex-staff', 'Ex-Staff'), ('ex-director/manager', 'Ex-Director/Manager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='idno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='krapin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='phoneno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='staffno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='sumassured',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='typeofcover',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('thirdparty', 'ThirdParty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='typeofvehicle',
            field=models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='yom',
            field=models.IntegerField(null=True),
        ),
    ]
