# Generated by Django 5.0.3 on 2024-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_alter_staffvehicle_area_alter_staffvehicle_chasisno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvehicle',
            name='sumassured',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
