# Generated by Django 5.0.3 on 2024-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_alter_staffvehicle_sumassured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='CommercialMotor',
        ),
        migrations.DeleteModel(
            name='DirectorsAndManagerMotor',
        ),
        migrations.DeleteModel(
            name='ExDirectorsAndManagerMotor',
        ),
        migrations.DeleteModel(
            name='ExStaffMotor',
        ),
        migrations.DeleteModel(
            name='PrivateMotor',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
        migrations.DeleteModel(
            name='StaffMotor',
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='chasisno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='commencementdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='logbook',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Cover Not Provided'), ('active', 'Cover Active'), ('cancelled', 'Cover Cancelled')], default='absent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='sumassured',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='yom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='regno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='logbook',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
