# Generated by Django 5.0.3 on 2024-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_delete_area_delete_commercialmotor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='typeofcover',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('thirdparty', 'ThirdParty')], max_length=100, null=True),
        ),
    ]
