# Generated by Django 5.0.3 on 2024-09-18 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_premium_annualpremium_alter_premium_refundstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvehicle',
            name='commencementdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='commencementdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='staffvehicle',
            name='commencementdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
