# Generated by Django 5.0.3 on 2024-09-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_alter_companyvehicle_commencementdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='dateofcancelorexpiry',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
