# Generated by Django 5.0.3 on 2024-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_alter_premium_commencementdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='premiumrate',
            field=models.FloatField(),
        ),
    ]
