# Generated by Django 5.0.3 on 2024-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_alter_premium_premiumrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='premiumrate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
