# Generated by Django 5.0.3 on 2024-09-18 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_alter_premium_premiumrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='amountpaid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='commencementdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='premium',
            name='dateofcancelorexpiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='premium',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='grandtotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='levies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('cashpayment', 'Cash Payment'), ('salarydeduction', 'Salary Deduction'), ('otherpayment', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='premiumpayable',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='staffno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Payment Made'), ('partpaid', 'Part Payment'), ('unpaid', 'Payment Not Made')], max_length=100, null=True),
        ),
    ]
