from django.urls import path
from . import views

urlpatterns = [
    path('computedpremium/<int:pk>/', views.computedpremium, name='computedpremium'),

    path('delete_staff_vehicle/<int:pk>/', views.delete_staff_vehicle, name='delete_staff_vehicle'),
    path('delete_company_vehicle/<int:pk>/', views.delete_company_vehicle, name='delete_company_vehicle'),
    path('delete_premium/<int:pk>/', views.delete_premium, name='delete_premium'),

    path('', views.home, name="home"),
    path('thankyou', views.thankyou, name="thankyou"),
    path('contactus', views.contactus, name="contactus"),

    path('comprehensivepremium', views.comprehensivepremium, name="comprehensivepremium"),
    path('thirdpartypremium', views.thirdpartypremium, name="thirdpartypremium"),

    path('export_thirdparty_premiums/', views.export_thirdparty_premiums, name='export_thirdparty_premiums'),
    path('export_comprehensive_premiums/', views.export_comprehensive_premiums, name='export_comprehensive_premiums'),

    path('premium/', views.premium, name="premium"),
    path('premiumform', views.premiumform, name="premiumform"),
    path('allpremium/', views.allpremium, name="allpremium"),
    path('paidpremium', views.paidpremium, name="paidpremium"),
    path('unpaidpremium', views.unpaidpremium, name="unpaidpremium"),
    path('partpaidpremium', views.partpaidpremium, name="partpaidpremium"),
    path('cashpayment', views.cashpayment, name="cashpayment"),
    path('salarydeduction', views.salarydeduction, name="salarydeduction"),
    path('otherpayment', views.otherpayment, name="otherpayment"),
    path('premiumrefund', views.premiumrefund, name="premiumrefund"),
    path('export_premiums/', views.export_premiums, name='export_premiums'),
    path('export_cash_payments/', views.export_cash_payments, name='export_cash_payments'),
    path('export_salary_deductions/', views.export_salary_deductions, name='export_salary_deductions'),
    path('export_other_payments/', views.export_other_payments, name='export_other_payments'),
    path('export_paid_premiums/', views.export_paid_premiums, name='export_paid_premiums'),
    path('export_unpaid_premiums/', views.export_unpaid_premiums, name='export_unpaid_premiums'),
    path('export_partpaid_premiums/', views.export_partpaid_premiums, name='export_partpaid_premiums'),
    path('export_refunded_premiums/', views.export_refunded_premiums, name='export_refunded_premiums'),
    path('searchallpremium', views.searchallpremium, name='searchallpremium'),
    path('premium/update/<int:pk>/', views.update_premium, name='update_premium'),


    path('companyvehicle', views.companyvehicle, name="companyvehicle"),
    path('companyvehicleform', views.companyvehicleform, name="companyvehicleform"),
    path('allcompanyvehicle/', views.allcompanyvehicle, name="allcompanyvehicle"),
    path('absentcompanyvehicle', views.absentcompanyvehicle, name="absentcompanyvehicle"),
    path('export_absent_company_vehicles/', views.export_absent_company_vehicles, name='export_absent_company_vehicles'),
    path('activecompanyvehicle', views.activecompanyvehicle, name="activecompanyvehicle"),
    path('cancelledcompanyvehicle', views.cancelledcompanyvehicle, name="cancelledcompanyvehicle"),
    path('export_active_company_vehicles/', views.export_active_company_vehicles, name='export_active_company_vehicles'),
    path('export_cancelled_company_vehicles/', views.export_cancelled_company_vehicles, name='export_cancelled_company_vehicles'),
    path('export-company-vehicles/', views.export_company_vehicles, name='export_company_vehicles'),
    path('companyvehicle/update/<int:vehicle_id>/', views.update_company_vehicle, name='update_company_vehicle'),
    path('searchallcompanyvehicle', views.searchallcompanyvehicle, name='searchallcompanyvehicle'),



    path('staffvehicle', views.staffvehicle, name="staffvehicle"),
    path('staffvehicleform', views.staffvehicleform, name="staffvehicleform"),
    path('allstaffvehicle/', views.allstaffvehicle, name="allstaffvehicle"),
    path('absentstaffvehicle', views.absentstaffvehicle, name="absentstaffvehicle"),
    path('export_absent_staff_vehicles/', views.export_absent_staff_vehicles, name='export_absent_staff_vehicles'),
    path('activestaffvehicle', views.activestaffvehicle, name="activestaffvehicle"),
    path('cancelledstaffvehicle', views.cancelledstaffvehicle, name="cancelledstaffvehicle"),
    path('currentstaffvehicle', views.currentstaffvehicle, name="currentstaffvehicle"),
    path('managervehicle', views.managervehicle, name="managervehicle"),
    path('exstaffvehicle', views.exstaffvehicle, name="exstaffvehicle"),
    path('exmanagervehicle', views.exmanagervehicle, name="exmanagervehicle"),
    path('privatevehicle', views.privatevehicle, name="privatevehicle"),
    path('commercialvehicle', views.commercialvehicle, name="commercialvehicle"),
    path('comprehensivecover', views.comprehensivecover, name="comprehensivecover"),
    path('thirdpartycover', views.thirdpartycover, name="thirdpartycover"),
    path('export-staff-vehicles/', views.export_staff_vehicles, name='export_staff_vehicles'),
    path('export_active_staff_vehicles/', views.export_active_staff_vehicles, name='export_active_staff_vehicles'),
    path('export_cancelled_staff_vehicles/', views.export_cancelled_staff_vehicles, name='export_cancelled_staff_vehicles'),
    path('export_current_staff_vehicles/', views.export_current_staff_vehicles, name='export_current_staff_vehicles'),
    path('export_managers_vehicles/', views.export_managers_vehicles, name='export_managers_vehicles'),
    path('export_ex_staff_vehicles/', views.export_ex_staff_vehicles, name='export_ex_staff_vehicles'),
    path('export_ex_managers_vehicles/', views.export_ex_managers_vehicles, name='export_ex_managers_vehicles'),
    path('export_private_vehicles/', views.export_private_vehicles, name='export_private_vehicles'),
    path('export_commercial_vehicles/', views.export_commercial_vehicles, name='export_commercial_vehicles'),
    path('export_comprehensive_vehicles/', views.export_comprehensive_vehicles, name='export_comprehensive_vehicles'),
    path('export_thirdparty_vehicles/', views.export_thirdparty_vehicles, name='export_thirdparty_vehicles'),
    path('update-vehicle/<int:vehicle_id>/', views.update_vehicle, name='update_vehicle'),
    path('staffvehicle/update/<int:vehicle_id>/', views.update_staff_vehicle, name='update_staff_vehicle'),
    path('searchallstaffvehicle', views.searchallstaffvehicle, name='searchallstaffvehicle'),
]